### ISSUE TITLE
图片应该要修改成可以用户配置模式

### ISSUE THREAD

**Issue by SSourceFile** [zhujiang521/Banner#1]
在使用中突然发现图片的contentScale属性设置crop和fiter的时候只能是crop，应该修改用户可配置化吧。不然为了这个功能还要重写BannerCard了

**Comment by zhujiang521** [comment]
我考虑不周了，周末的时候我更新下

发自我的iPhone

**Comment by zhujiang521** [comment]
最新版本1.5.0已经增加此功能，暂时关闭此问题
